# Generated by Django 5.2 on 2025-05-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='conteudo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
