# Generated by Django 5.2 on 2025-05-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_noticia_conteudo2_noticia_descricao_noticia_imagem2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
