# Generated by Django 5.2 on 2025-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_noticia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('vulnerabilidades', 'Vulnerabilidades'), ('ameaças', 'Ameaças'), ('tendências', 'Tendências'), ('cibersegurança', 'Cibersegurança em geral')], max_length=100),
        ),
    ]
