# Generated by Django 5.2 on 2025-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descricao_imagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
