# Generated by Django 5.2 on 2025-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_noticia_descricao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descricao_imagem2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
